#DataBase
MYSQL_USERNAME: root
MYSQL_PASSWORD: root
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: securecapita

#Server config
CONTAINER_PORT: 8082
#ACTIVE_PROFILE: test

#JWT config
JWT_SECRET: secretcodeprod

UI_APP_URL: http://localhost:4200




