application:
    title: SecureCapita
    version: 1.0

spring:
    #autoconfigure:
    #    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    profiles:
        active: ${ACTIVE_PROFILE:dev}
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:securecapita}
        password: ${MYSQL_PASSWORD:root}
        username: ${MYSQL_USERNAME:root}
    jpa:
        database-platform: org.hibernate.dialect.MySQL8InnoDialect
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                globally_quoted_identifiers: true
                format_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect
    sql:
        init:
            mode: always
            continue-on-error: false

server:

    error:
        path: /user/error
        whitelabel:
            enabled: false
    port: ${CONTAINER_PORT:8081}


jwt:
    secret: ${JWT_SECRET:secretcode}

ui:
    app:
        url: ${UI_APP_URL}


